// const String BASE_URL = 'http://192.168.1.34:9800'; //change it to localhost or your ip address if you want it to work on a phone
const String BASE_URL = 'http://localhost:9800'; //change it to localhost or your ip address if you want it to work on a phone
const String LOGIN_URL = 'api/auth/login';
const String REGISTER_URL = 'api/auth/register';
const String ADD_CAR_URL = 'api/cars';
const String GET_CAR_URL = 'api/cars';
const String BECOME_AGENCY_URL = 'api/auth/becomeAgency'; 
const String CREATE_BOOKING_URL = 'api/bookings'; 
const String GET_BOOKING_URL = 'api/bookings'; 
